name: docs-on-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: copy content
        run: cp ./README.md ./docfx_project/index.md
      
      - name: Generate build
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docfx_project/docfx.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./docfx_project/_site
