name: Create Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Github-Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'com.org-name.package-name.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
