name: Create Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Github-Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'package-name.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "package-name.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
