name: Node.js Package

on:
  push:
    branches:
      - main
    tags:
      - v0*.**.*

jobs:

  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
